server:
  port: 8083
  
spring:
  application:
    name: ami-persistence-service
      
  cloud:
    function:
      definition: handleNewMeterData15min;handleNewMeterData1hour;handleNewMeterData1day

    stream:
      kafka:
        binder:
          brokers: 192.168.196.130:9092          
          autoCreateTopics: true
          minPartitionCount: 2
          replicationFactor: 1
      
      bindings:
        handleNewMeterData15min-in-0:
          destination: csu-utility.ami.raw.15min
          group: csu-utility.ami.raw.15min
          consumer:
            batch-mode: true
        handleNewMeterData1hour-in-0:
          destination: csu-utility.ami.hourly
          group: csu-utility.ami.hourly
          consumer:
            batch-mode: true
        evAnalysisTriggers-in-0:
          destination: csu-utility.ami.hourly
          group: csu-utility.ev-analysis-triggers
        handleNewMeterData1day-in-0:
          destination: csu-utility.ami.daily
          group: csu-utility.ami.daily
          consumer:
            batch-mode: true
          
  mongodb:
    uri: mongodb://192.168.196.130:2717/
    database: agg_meter_data_db
    autoIndexCreation: true

tenant.id: csu-utility
ev.analysis.frequency.days: 10